name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            docker build -t benim-uygulamam .
            docker stop my-web-app || true
            docker rm my-web-app || true
            docker run -d -p 80:80 --name my-web-app benim-uygulamam
            echo "Deploy islemi basariyla tamamlandi!"